name: Permissions
main: com.nijikokun.bukkit.Permissions.Permissions
version: 3.1.4
authors:
  - TheNo1Yeti
  - rcjrrjcr
  - Nijikokun
website: www.theyeticave.net
description: >
             Provides a Permissions framework for use with Bukkit Plugins
commands:
  permissions:
    aliases: [perms, pr]
    description: Provides access to Permissions commands and information.
    usage: |
           /pr | Displays Permissions Info
           /pr -reload | Reloads the default world
           /pr -reload all | Reloads all worlds
           /pr -reload [world] | Reloads [world]
           /pr (g:)<target> (w:<targetworld>) (action) (actionparams) | Directs (action) on specified group/user.
